### ISSUE TITLE
Typo In URLS For Pip-install

### ISSUE THREAD

**Issue by tbpassin** [IBM/neuro-vsa#1]
The URLs given for pip-installing contain a ":" where there should be a "/":

`pip install git+https://github.com:IBM/neuro-vector-symbolic-architectures.git`

should be

`pip install git+https://github.com/IBM/neuro-vector-symbolic-architectures.git`

These URLs don't work as given.

**Comment by MHersche** [comment]
Thanks for the hint. It's resolved.
